# module name must be max 8 characters (8.3 file name on the card)
MODULE_NAME = grainovl
MODULE_OBJS = $(BUILD_DIR)/grain_overlay.o
TOP_DIR = ../..

# include modules environment
include $(TOP_DIR)/modules/Makefile
.DEFAULT_GOAL := $(BUILD_DIR)/module_complete
